# services:
#   - type: web
#     name: grapeguard-backend
#     runtime: python
#     buildCommand: |
#       cd backend &&
#       python -m pip install --upgrade pip &&
#       pip install torch==2.3.1 torchvision==0.18.1 --index-url https://download.pytorch.org/whl/cpu &&
#       pip install 'git+https://github.com/facebookresearch/detectron2.git' &&
#       pip install -r requirements.txt
#     startCommand: cd backend && gunicorn detectron_server:app
#     plan: free
#     pythonVersion: "3.11"


services:
  - type: web
    name: grapeguard-backend
    runtime: python
    plan: starter
    pythonVersion: "3.11.9"
    buildCommand: |
      python -m pip install --upgrade pip &&
      pip install torch==2.0.1+cpu torchvision==0.15.2+cpu --find-links https://download.pytorch.org/whl/torch_stable.html &&
      pip install numpy==1.24.3 opencv-python-headless==4.8.1.78 Pillow==10.0.1 &&
      pip install Flask==2.3.3 Flask-CORS==4.0.0 gunicorn==21.2.0 python-dotenv==1.0.0 &&
      pip install pycocotools==2.0.7 iopath fvcore &&
      pip install git+https://github.com/facebookresearch/detectron2.git
    startCommand: gunicorn detectron_server:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    env:
      - key: DETECTRON_MODEL_PATH
        value: "./model_final.pth"
      - key: DETECTRON_THRESHOLD  
        value: "0.7"
      - key: FLASK_ENV
        value: "production"