services:
  - type: web
    name: grapeguard-backend
    runtime: python
    plan: starter
    pythonVersion: "3.10.11"
    buildCommand: |
      chmod +x backend/build.sh
      ./backend/build.sh
    startCommand: gunicorn backend.detectron_server:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    env:
      - key: DETECTRON_MODEL_PATH
        value: "./backend/model_final.pth"
      - key: DETECTRON_THRESHOLD  
        value: "0.7"
      - key: FLASK_ENV
        value: "production"